log:
  level: info

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 1024
      lazy_cache_ttl: 86400

  # 匹配本地域名
  - tag: match_is_local_domain
    type: domain_set
    args:
      files:
        - path: /usr/share/v2ray/geosite.dat
          type: geosite
          args: cn

  # 匹配非本地域名
  - tag: match_is_non_local_domain
    type: domain_set
    args:
      files:
        - path: /usr/share/v2ray/geosite.dat
          type: geosite
          args: geolocation-!cn

  # 匹配广告域名
  - tag: match_is_ad_domain
    type: domain_set
    args:
      files:
        - path: /usr/share/v2ray/geosite.dat
          type: geosite
          args: category-ads-all

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: ip_set
    args:
      files:
        - path: /usr/share/v2ray/geoip.dat
          type: geoip
          args: cn

  # 转发至本地服务器 DNSPod
  - tag: forward_local
    type: fast_forward
    args:
      upstreams:
        - addr: https://1.12.12.12/dns-query

  # 转发至远程服务器 DNS.SB
  - tag: forward_remote
    type: fast_forward
    args:
      upstreams:
        - addr: https://45.11.45.11/dns-query

  # fallback 用本地服务器 sequence
  # 返回不包含本地 ip 则 reject
  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $forward_local
      - matches: resp_ip $response_has_local_ip
        exec: accept
      - exec: reject

  # fallback 用远程服务器 sequence
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: accept

  # fallback 用远程服务器 sequence
  - tag: "fallback"
    type: "fallback"
    args:
      primary: local_ip_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      - matches: qname $match_is_ad_domain
        exec: reject
      - exec: $cache
      - matches: has_resp
        exec: accept
      - matches: qname $match_is_local_domain
        exec: $forward_local
      - matches: qname $match_is_non_local_domain
        exec: $forward_remote
      - exec: $fallback

  # 启动 udp 服务器。
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: 127.0.0.1:53

  - tag: udp_server_v6
    type: udp_server
    args:
      entry: main_sequence
      listen: "[::1]:53"
